gemfile: Gemfile

# 不要なチェックを無効化
CommitMsg:
  ALL:
    enabled: false
PreCommit:
  AuthorEmail:
    enabled: false
  AuthorName:
    enabled: false
  BrokenSymlinks:
    enabled: false
  CaseConflicts:
    enabled: false
  MergeConflicts:
    enabled: false
# 必要なチェックの設定
  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop', '-c', '.rubocop.yml']
  RailsBestPractices:
    enabled: true
    command: ['bundle', 'exec', 'rails_best_practices', '-c', 'config/rails_best_practices.yml']
PrePush:
  RSpec:
    enabled: true
    command: ['bundle', 'exec', 'rspec']
