# 数学I
- id: 10
  name: "数と式・集合と論理"
  subject: I
- id: 20
  name: "図形と計量"
  subject: I
- id: 30
  name: "二次関数"
  subject: I
- id: 40
  name: "データの分析"
  subject: I

  # 数学A
- id:
  name: "場合の数"
  subject: A
- id: 110
  name: "確率"
  subject: A
- id: 120
  name: "整数"
  subject: A
- id: 130
  name: "図形の性質"
  subject: A

# 数学II
- id: 210
  name: "式と証明"
  subject: II
- id: 220
  name: "複素数と方程式"
  subject: II
- id: 230
  name: "図形と方程式"
  subject: II
- id: 240
  name: "三角関数"
  subject: II
- id: 250
  name: "指数・対数関数"
  subject: II
- id: 260
  name: "微分"
  subject: II
- id: 270
  name: "積分"
  subject: II

  # 数学B
- id: 310
  name: "平面ベクトル"
  subject: B
- id: 320
  name: "空間ベクトル"
  subject: B
- id: 330
  name: "数列"
  subject: B
- id: 340
  name: "確率分布と統計的な推測"
  subject: B

# 数学III
- id: 410
  name: "複素数平面"
  subject: III
- id: 420
  name: "式と曲線"
  subject: III
- id: 430
  name: "関数"
  subject: III
- id: 440
  name: "極限"
  subject: III
- id: 450
  name: "微分"
  subject: III
- id: 460
  name: "積分"
  subject: III
