site:
  name: "入試数学の広場"

url:
  google_form: "https://docs.google.com/forms/d/e/1FAIpQLSeazz0uwwS1lxEqDMTBW24SwA-4K4KRRnd_3MRSV1TxoXCzSg/viewform?usp=sf_link"
  twitter: "#"

admin_tex_default_code: "\\documentclass[17pt, dvipdfmx]{jsarticle}\
                        \r\n\
                        \\usepackage{amssymb, amsmath, tikz, enumerate}\
                        \r\n\
                        \\usetikzlibrary{intersections, calc, arrows.meta, math}\
                        \r\n\
                        \\usepackage[margin=1cm]{geometry}\
                        \r\n\
                        \\pagestyle{empty}\
                        \r\n\
                        \r\n\
                        \\begin{document}\
                        \r\n\
                        \r\n\
                        \\end{document}"

tex_default_code: "\\documentclass[12pt, dvipdfmx]{jsarticle}\
                  \r\n\
                  \\usepackage{amssymb, amsmath, tikz, enumerate}\
                  \r\n\
                  \\usetikzlibrary{intersections, calc, arrows.meta, math}\
                  \r\n\
                  \\usepackage[margin=1cm]{geometry}\
                  \r\n\
                  \\pagestyle{empty}\
                  \r\n\
                  \r\n\
                  \\begin{document}\
                  \r\n\
                  \r\n\
                  \\end{document}"
