tex_default_code: "\\documentclass[12pt, dvipdfmx]{jsarticle}
                  \r\n
                  \\usepackage{amssymb, amsmath, tikz}
                  \r\n
                  \\usetikzlibrary{intersections, calc, arrows.meta, math}
                  \r\n
                  \\usepackage[margin=1cm]{geometry}
                  \r\n
                  \\pagestyle{empty}
                  \r\n
                  \r\n
                  \\begin{document}
                  \r\n
                  \r\n
                  \\end{document}"
