#tmp_pdf_path: <%= Rails.root.join("tmp/rails-latex/") %><%= Time.current.strftime("%Y%m%d%H%M%S") %>.pdf
tmp_png_path: <%= Rails.root.join("tmp/rails-latex/") %><%= Time.current.strftime("%Y%m%d%H%M%S") %>.png
# 後にユーザーuuidをファイル名に加える

host: "localhost:3000"
