tmp_pdf_path: <%= Rails.root.join("tmp/rails-latex/") %><%= I18n.l(Time.current, format: :long) %>.pdf
tmp_png_path: <%= Rails.root.join("tmp/rails-latex/") %><%= I18n.l(Time.current, format: :long) %>.png
# 後にユーザーuuidをファイル名に加える
