name: "Ruby on Rails CI"
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      # Add or replace dependency steps here
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          bundler-cache: true
          ruby-version: 3.1.1
      - name: Set up yarn and node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'
      - name: yarn install
        run: yarn install

      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Install chrome
        uses: browser-actions/setup-chrome@latest
      - name: Install font
        run: sudo apt install fonts-ipafont fonts-ipaexfont
      # Add or replace test runners here
      - name: run systemspec
        run: bundle exec rspec spec/system
      # システムスペック失敗時にスクリーンショットを取得
      - name: Archive systemspec result screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: systemspec result screenshots
          path: tmp/screenshots/
      - name: run modelspec
        run: bundle exec rspec spec/models
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          bundler-cache: true
          ruby-version: 3.1
      - name: rails_best_practices
        run: bundle exec rails_best_practices
      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-performance:gemfile
          reporter: github-pr-check
