name: "Ruby on Rails CI"
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      # Add or replace dependency steps here
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.1.1
      - name: Set up yarn and node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'
      - name: yarn install
        run: yarn install
      # libvips をインストール
      - name: install libvips
        run: sudo apt install libvips42
      - name: remove adminlte scss files
        run: rm -r node_modules/admin-lte/build/scss
      # webpackerにerbサポートを追加する
      - name: webpacker install erb
        run: bin/rails webpacker:install:erb
      - name: compile assets
        run: bin/webpack
      # db/schema.rbが存在することをチェックする
      - name: Check schema existence
        id: check_schema_file
        uses: andstor/file-existence-action@v1
        with:
          files: "db/schema.rb"
      # Add or replace database setup steps here
      # db/schema.rbが存在するときは、DBを作成
      - name: Set up database schema
        if: steps.check_schema_file.outputs.files_exists == 'true'
        run: bin/rails db:schema:load
      # ブラウザchromeをインストール
      - name: Install chrome
        uses: browser-actions/setup-chrome@latest
      - name: Install font
        run: sudo apt install fonts-ipafont fonts-ipaexfont
      # TexLiveをインストール
      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v2
        with:
          version: 2022
      - name: Check `tlmgr` version
        run: tlmgr --version
      - name: create tex path
        run: |
          echo 'export PATH=$RUNNER_TEMP/setup-texlive/2022/bin/x86_64-linux:$PATH' >> ~/.bashrc
          platex -version
          ls -al `which platex`
      - name: add permission for platex_dvipdfmx.sh
        run: sudo chmod +x lib/tasks/platex_dvipdfmx.sh
      - name: add permission for platex_dvipdfmx.sh
        run: sudo chmod +x lib/tasks/platex_dvipdfmx.sh
      # spec/system/ にファイルがあることをチェック
      - name: Check systemspec existence
        id: check_systemspec_files
        uses: andstor/file-existence-action@v1
        with:
          files: "spec/system/"
      # spec/system/ にファイルがあるときシステムスペックを実行
      - name: run systemspec
        if: steps.check_systemspec_files.outputs.files_exists == 'true'
        run: bundle exec rspec spec/system/
      # システムスペック失敗時にスクリーンショットを取得
      - if: failure()
        name: Archive systemspec result screenshots
        uses: actions/upload-artifact@v3
        with:
          name: systemspec result screenshots
          path: tmp/screenshots/
      # spec/models/ にファイルがあることをチェック
      - name: Check modelspec existence
        id: check_modelspec_files
        uses: andstor/file-existence-action@v1
        with:
          files: "spec/models/"
      # pec/models/ にファイルがあるときモデルスペックを実行
      - name: run modelspec
        if: steps.check_modelspec_files.outputs.files_exists == 'true'
        run: bundle exec rspec spec/models/
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.1.1
      - name: rails_best_practices
        run: bundle exec rails_best_practices
      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          skip_install: true
          use_bundler: true
          reporter: github-pr-check
